### ISSUE TITLE
Return true piped url for more readable

### ISSUE THREAD

**Issue by NoPlagiarism** [TeamPiped/instances-api#13]
By that, I mean add sth like `"domain": "piped.{name}"` or full url instead

**Comment by FireMasterK** [comment]
This won't be done, since I'm not willing to do any checks for instances' compliance with the AGPL license.

Hence they're a "use at your own risk" kind of thing.

**Comment by NoPlagiarism** [comment]
> Hence they're a "use at your own risk" kind of thing.

So... They exists, but they do not exists... OK
