### ISSUE TITLE
Can't parse url without registered users badge

### ISSUE THREAD

**Issue by NoPlagiarism** [TeamPiped/instances-api#14]

**Comment by FireMasterK** [comment]
I'm not sure what this is supposed to mean.

Could you ellaborate further?

**Comment by NoPlagiarism** [comment]
Check response. For example those domains not parsed by main.go

- mint.lgbt
- tokhmi.xyz
- privacy.com.de
- plibre.com

**Comment by FireMasterK** [comment]
> Check response. For example those domains not parsed by main.go
> 
> - mint.lgbt
> - tokhmi.xyz
> - privacy.com.de
> - plibre.com

All those instances don't pass the healthcheck.

For example: https://pa.mint.lgbt/healthcheck

**Comment by NoPlagiarism** [comment]
Ok, sry for that
